### ISSUE TITLE
能否在API上兼容下Dialog

### ISSUE THREAD

**Issue by xiandanin** [Jacksgong/JKeyboardPanelSwitch#102]
KPSwitchConflictUtil中很多方法都是直接强转Activity的，我如果用的是Dialog，getContext()拿到的实际是`ContextThemeWrapper`
```
final Activity activity = (Activity) panelLayout.getContext();
```

虽然可以自己改下源码然后用，但是没有Gradle引入方便

**Comment by hysea** [comment]
你是怎么在Dialog中处理的，能否给个demo看看

**Comment by xiandanin** [comment]
@hysea 
[JKeyboardPanelSwitch/ExampleDialog](https://github.com/dengyuhan/JKeyboardPanelSwitch/blob/support/app/src/main/java/cn/dreamtobe/kpswitch/demo/activity/ExampleDialog.java)

[PanelKeyboardCompat/ExampleDialog](https://github.com/dengyuhan/PanelKeyboardCompat/blob/master/app/src/main/java/com/dyhdyh/widget/panelkeyboard/example/dialog/ExampleDialog.java)

**Comment by hysea** [comment]
谢了哈
