### ISSUE TITLE
全屏界面在一些特殊情况下还是会有问题

### ISSUE THREAD

**Issue by vailWei** [Jacksgong/JKeyboardPanelSwitch#12]
第一次进去的时候，会有个50dp的高度差（title有50dp被顶到屏幕外，键盘和edittext的那个linearlayout之间隔50dp）。大概是没有考虑到这种情况吧。

**Comment by Jacksgong** [comment]
不是很明白你说的，目前应该是覆盖所有case，除非，应用新安装，第一次还不知道键盘高度，在这个应用新安装第一次使用的情况，会有一点点问题，一旦获得键盘高度，就不会有问题了。

如果你的问题不是这个，稍微提供下demo的project，我看看。

**Comment by vailWei** [comment]
我把有问题的地方截图上传了。https://github.com/vailWei/Android-/blob/master/device-2016-03-28-105310.png

**Comment by Jacksgong** [comment]
:+1: 我并非怀疑你提出来的问题，只是不知道在什么case下。

**Comment by vailWei** [comment]
第一张截图是第一次进应用，正如你所说，第一次是有问题的。第二张截图是在ChattingResolvedFullScreenActivity时，按home键，然后返回，界面就显示有问题了。接下来操作就恢复正常了

**Comment by Jacksgong** [comment]
:100: 恩。 谢谢你的细心，应用提到的第一个问题，我之后有空了会花时间研究下的（其实有一些取巧的解决方案，应该我们的解决方法是基于获知键盘高度的）。

不过，至于home键这个我这边用项目中的demo，无法复现，不知还有哪些细节没有覆盖到。可以看下我操作gif:

https://cloud.githubusercontent.com/assets/6176417/14070184/d6c92236-f4d5-11e5-8cd4-28e489905f13.gif

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6176417/14070184/d6c92236-f4d5-11e5-8cd4-28e489905f13.gif)

**Comment by vailWei** [comment]
键盘弹出来一次后，然后让键盘收起来，键盘收起来的的情况下按home键

**Comment by Jacksgong** [comment]
:8ball: ....奇怪了，我这边没有遇到你提到的问题诶。。。还有什么细节遗漏吗。

https://cloud.githubusercontent.com/assets/6176417/14070587/fa22f072-f4da-11e5-8691-021bd0bc9ea4.gif

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/6176417/14070587/fa22f072-f4da-11e5-8691-021bd0bc9ea4.gif)

https://cloud.githubusercontent.com/assets/6176417/14070668/02e7d80c-f4dc-11e5-9510-a5403cd84867.gif

![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/6176417/14070668/02e7d80c-f4dc-11e5-9510-a5403cd84867.gif)

**Comment by kongnanlive** [comment]
![b467c5cea4023d1416e6d0e2dbe3836f](https://cloud.githubusercontent.com/assets/2374686/14071833/fa810cb4-f4eb-11e5-9339-cb39e14630ca.jpg)
键盘在打开的情况下按下home键，然后在回来就是这样了。

**Comment by baitouwei** [comment]
我按照以下操作会重新上面的两个 bug。
Bug 1：进入全屏界面->点击输入框弹起键盘->点击 Home 键回到桌面->再回到 App，发现有位移。
![bug1](https://cloud.githubusercontent.com/assets/1253712/14074892/0b365dc8-f507-11e5-99f4-9ef5eef03306.gif)

Bug 2：进入全屏界面->点击输入框弹起键盘->点击返回键缩回键盘->点击 Home 键回到桌面->再回到 App，发现 Title 不见了。
![bug2](https://cloud.githubusercontent.com/assets/1253712/14074919/4db99ef8-f507-11e5-8ba8-3b21b474c895.gif)

**Comment by Jacksgong** [comment]
@baitouwei :100: bug2我复现了，我抽空处理下，不过也许是机型的问题bug1我无法复现。

**Comment by kongnanlive** [comment]
@Jacksgong 有时间解决第一次进应用的bug时@我一下 就差这个就完美了。

**Comment by Jacksgong** [comment]
@baitouwei 

#### 我修复了你提到的bug2

> Bug 2：进入全屏界面->点击输入框弹起键盘->点击返回键缩回键盘->点击 Home 键回到桌面->再回到 App，发现 Title 不见了。

我说下修复的基本原理: 这个bug是因为在EditText上面保留了focus，虽然我们收回了键盘，但是在 `windowSoftInputMode` 为 `stateUnspecified`(这个为默认值，在这个case下我们没有配置，因此就是这个默认值)的情况下，返回的时候如果布局上存在focus的 `EditText`就会自动将键盘唤起。 我们解决冲突的逻辑就是在键盘起来之前先用一个与键盘等高的布局将 `EditText` 顶到我们需要的高度。因此这个Case解决办法有两种:

1.  在 `onResume` 的地方，在这次返回桌面再进入的时候，在键盘弹起之前，主动将 `panelRoot` 这个键盘等高布局 显示出来，故 `panelRoot.setVisibility(View.INVISIBLE)`。这样，在进来的时候虽然键盘随着已存在的 focus 弹起了，但是布局不会出现问题。

2. 在 `onPause` 的地方，直接将 focus 释放，故 `sendEdt.clearFocus()`，这样再从桌面再次进入的时候，由于不存在 focus 键盘就不会主动弹起，因此就不会有这个问题。 (P.S: 因为在我们的demo里面，我们预期收回键盘以后下次再进入不用主动弹起键盘，因此我采用了这个解决方法。[6395eb8](https://github.com/Jacksgong/JKeyboardPanelSwitch/commit/6395eb8bae3a493c48f050d24dc5ab35c858a0a4))

**Comment by Jacksgong** [comment]
@baitouwei @vailWei 我发现你们提到的bug1这个与输入法有关，谷歌输入法也许是比较轻量，弹起的比较早，因此就遇到了这个问题，当然有一个有损体验快速解决这个问题，就是在 `onPause` 的时候，直接将 focus clear 掉，这样，回来就不会有布局上的这个问题。

我抽空会看看这个bug的解决方案的。

**Comment by baitouwei** [comment]
👍效率真高

**Comment by vailWei** [comment]
赞一个，效率真是高
