### ISSUE TITLE
请问下如果输入控件是在自定义的dialog中，该如何处理？

### ISSUE THREAD

**Issue by jtyang** [Jacksgong/JKeyboardPanelSwitch#15]
请问下如果输入控件是在自定义的dialog中，该如何处理？目前通过监听activity的方式貌似就不行了。
谢谢！

**Comment by Jacksgong** [comment]
这个使我想起了之前 #4 这个问题的处理，当时就是在dialog中，你可以先看看。我抽空再看看具体情况。
