### ISSUE TITLE
微信用的是这个方式吗？

### ISSUE THREAD

**Issue by ChanningSun** [Jacksgong/JKeyboardPanelSwitch#18]
如果是，会不会涉及到泄密呢？

**Comment by Jacksgong** [comment]
是的，这个库是基于之前我在微信上的实现，迭代起来的。

这个并非机密，基于微信内部的思想，我想对于这类代码不存在泄密的问题。所谓的源码代码本身是没有价值的，有价值的是迭代与维护，是人，是社区。

我个人认为，只要不涉及业务层逻辑以及核心竞争力(比如微信的小视频、Build、架构等，还有以前我参与的Wechat-SVG)，所有的代码都没有机密可言，在基于LICENSE的前提下没有必要为了某些技术研究结果藏着掖着，开源会使技术进一步推进，所有的技术都具有绝对的时效性。

> P.S: 之前在微信做过很多研究，这个键盘处理只是很多技术中的其中一个小点。
