### ISSUE TITLE
compile 'cn.dreamtobe.kpswitch:library:1.4.1' 类找不到

### ISSUE THREAD

**Issue by 275873859** [Jacksgong/JKeyboardPanelSwitch#19]
compile 'cn.dreamtobe.kpswitch:library:1.4.1' 引用这个，类都找不到，但compile 'cn.dreamtobe.kpswitch:library:1.3.0' 就没问题

**Comment by Jacksgong** [comment]
> 多谢你的好意，不过应该是有的，你检查下你的网络。再试试。再check下你的 `repositories`是否有配置 `jcenter()` 或者 `marvinCentral()`。

#### 这个是MarvinCentral仓库上的:

https://oss.sonatype.org/content/repositories/releases/cn/dreamtobe/kpswitch/library/1.4.1/

![image](https://cloud.githubusercontent.com/assets/6176417/14280697/e1d44b82-fb66-11e5-94b0-6283441a0156.png)



#### 这个是Jcenter仓库上的:

http://jcenter.bintray.com/cn/dreamtobe/kpswitch/library/1.4.1/

![image](https://cloud.githubusercontent.com/assets/6176417/14280736/2f7a1524-fb67-11e5-968a-31cd17e4ea0e.png)

**Comment by Jacksgong** [comment]
或者你clean下，再re-build下，有可能是ide的坑，也有可能是国内网络的坑。还有什么问题，同步到这个issue。

**Comment by 275873859** [comment]
谢谢，问题终于解决了，使用之前下载好的 gradle 后，都在本地能搜到那些 jar aar文件了，但还是不能调用，改用推荐的 gradle 就好了

**Comment by Jacksgong** [comment]
:100:

**Comment by Jacksgong** [comment]
> P.S: 建议使用 目前最新版本 1.4.2，避免在混淆的时候 混淆不过。
