### ISSUE TITLE
让 ChattingResolvedActivity extends FragmentActivity ；一直点击"+"那个图片 会有闪动

### ISSUE THREAD

**Issue by zhouzhiqiangzzq** [Jacksgong/JKeyboardPanelSwitch#21]
让 ChattingResolvedActivity extends FragmentActivity ；一直点击"+"那个图片 会有闪动

**Comment by Jacksgong** [comment]
💯 我看到了，我一会儿修复下提交。

**Comment by Jacksgong** [comment]
@zhouzhiqiangzzq 已经修复了，你拉取最新代码试试，感谢你的提醒。

**Comment by LynLin0** [comment]
让 ChattingResolvedActivity extends FragmentActivity 时，按照你的说法，可能是存在actionBarOverlayLayout.getPaddingTop()!=0的情况。
在calculateKeyboardShowing中
actionBarOverlayLayoutHeight的= displayHeight+actionBarOverlayLayout.getPaddingTop()，
这导致当键盘不显示时本应执行的
 if (displayHeight >= maxOverlayLayoutHeight) {
                    isKeyboardShowing = false;
} 
不被执行，
那么其他地方调用panelLayout.isKeyboardShowing的代码应该也会有问题，是否存在这种问题呢
