### ISSUE TITLE
windowsTranslucentStatus 为 true时有问题。

### ISSUE THREAD

**Issue by anjiao** [Jacksgong/JKeyboardPanelSwitch#26]
Nexus 5 +  搜狗输入法 高度计算有问题！？我这里不行 全屏的可以

**Comment by Jacksgong** [comment]
我一直就是以 Nexus5 + 搜狗输入法 这样的配置测试的，不知道你是什么具体case。

**Comment by Jacksgong** [comment]
这是我刚刚录制的Gif:  https://cloud.githubusercontent.com/assets/6176417/14714398/6979dd9c-0817-11e6-90aa-f31682831b73.gif

![ezgif com-video-to-gif 6](https://cloud.githubusercontent.com/assets/6176417/14714398/6979dd9c-0817-11e6-90aa-f31682831b73.gif)

**Comment by anjiao** [comment]
输入法 盖着 那个输入框
<cn.dreamtobe.kpswitch.widget.KPSwitchRootLinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/rootView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    

    <LinearLayout
        android:orientation="vertical"
        android:background="@color/default_bg"
        android:layout_width="match_parent"
        android:layout_height="200dip"/>

    <ListView
        android:id="@+id/content_ryv"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1.0"
        android:background="@color/chatting_list_bg" />


    <include layout="@layout/layout_send_message_bar" />


    <cn.dreamtobe.kpswitch.widget.KPSwitchPanelLinearLayout
        android:id="@+id/panel_root"
        style="@style/Panel"
        android:visibility="gone">

        <include layout="@layout/merge_panel_content" />
    </cn.dreamtobe.kpswitch.widget.KPSwitchPanelLinearLayout>

</cn.dreamtobe.kpswitch.widget.KPSwitchRootLinearLayout>

**Comment by Jacksgong** [comment]
你看下你是否是继承自 FragmentActivity 或者是 Activity，如果是的话，用前两天发的最新版本，已经修复了。

**Comment by anjiao** [comment]
setContentView(R.layout.activity_chatting_resolved);

        WindowManager.LayoutParams localLayoutParams = getWindow().getAttributes();
        localLayoutParams.flags = (WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS | localLayoutParams.flags);


我试了试  好像和我加了这个有关 你加上这个 就不行了

**Comment by Jacksgong** [comment]
哦。那我知道了。我会把这个问题处理掉的。

**Comment by Jacksgong** [comment]
跟下这个问题就行: #27

**Comment by anjiao** [comment]
好的谢谢  有空更新下呀 大神
