### ISSUE TITLE
今天在使用时，突然发现如果页面是一些自定主View的时候，比如是带下拉刷新的ListView的话，触摸事件和点击事件都失效了..

### ISSUE THREAD

**Issue by zhangjinhuang** [Jacksgong/JKeyboardPanelSwitch#29]
今天在使用时，突然发现如果页面是一些自定主View的时候，比如是带下拉刷新的ListView的话，触摸事件和点击事件都失效了..

**Comment by Jacksgong** [comment]
应该是和这个库没有关系的，这个库并没有处理相关事件。

**Comment by alanforgithub** [comment]
我直接运行Demo也是这样的，您可以看一下，直接打开第一个开关的背景是灰色的，手动开关一下背景色就恢复正常的白色了，请看下效果图。
![Uploading 屏幕截图效果.png…]()

**Comment by Jacksgong** [comment]
@alanforgithub 我不是很明白你说的，能具体点吗？

**Comment by alanforgithub** [comment]
@Jacksgong ，不好意思，回复错了。。。^+^

**Comment by Jacksgong** [comment]
@alanforgithub :)
