### ISSUE TITLE
RootLayout 里有些地方不太明白

### ISSUE THREAD

**Issue by eling13** [Jacksgong/JKeyboardPanelSwitch#3]
onMeasure、onLayout、onGlobalLayout 分别在这三个里面做不同的处理
话说能不能只在一个里面做所有的处理啊？

**Comment by Jacksgong** [comment]
恩。是有原因的。你可以先结合  [Switching between the panel and the keyboard in Wechat](http://blog.dreamtobe.cn/2015/02/07/Switching-between-the-panel-and-the-keyboard/)与 [Android键盘面板冲突 布局闪动处理方案](http://blog.dreamtobe.cn/2015/09/01/keyboard-panel-switch/) 这两篇文章看下。我晚上下班回去给你整理下，解答给你。

**Comment by Jacksgong** [comment]
其实认真一看，这是个很好的问题，可以解答几乎所有需要注意的点。很感谢你的提问。

### 第一个问题: onMeasure、onLayout、onGlobalLayout 分别在这三个里面做不同的处理

#### 为什么需要在`CustomRootLayout`的`onMeasure`中判断，而不是其他地方判断是否是真正键盘引起变化的?

对于我们可见的'最早'获知布局变化的，就是`CustomRootLayout`的`onMeasure`，其次，必须要在`PanelLayout`的`onMeasure`之前获知，因此比较恰当的地方就是`CustomRootLayout`的`onMeasure`甚至更早。

#### 为什么需要在`PanelLayout`的`onMeasure`中做防止面板闪现而不是其他地方?

如果在onLayout或者其他点中处理，都没有`onMeasure`中处理简单，`PanelLayout`的`onMeasure`结果的影响不仅仅是`PanelLayout`自己将要进行的大小layout，还有其他View的布局layout与大小。

#### 为什么要在`CustomRootLayout`的`onLayout`来判断是否键盘弹起，而不是其他地方?

`CustomRootLayout`的`onLayout`中判断，是准确与获知变化时间比较早 的权衡结果。

#### 为什么要在`onGlobalLayout`中处理真正的键盘变化并且进行键盘变化存储?

由于`onMeasure`与`onLayout`可能被多次调用，而`onGlobalLayout`是布局变化后只会被一次调用，因此在`onGlobalLayout`中计算键盘高度变化以及有效高度进行存储更为恰当。

### 第二个问题: 能不能只在一个里面做所有的处理啊?

我们需要最早的布局变化中获知是否是键盘变化，至少要比面板大小变化进而导致布局变化之前获知，因此这里就无法避免就引入了两个View, 对于我们可见的顶级布局(`CustomRootLayout`)与面板布局(`PanelLayout`)。

**Comment by jiangtingfu** [comment]
在自定义面板消失，软键盘弹起的时候有个小小的黑色的过度，这里感觉上不是那么的完美，其他的都已经非常OK了。

我发现现在的微信，QQ，包括我自己手机的短信的软键盘和自定义面板切换没有这种现象了，希望楼主研究下。

**Comment by Jacksgong** [comment]
那个黑色是你的主题背景色，也就是window的颜色。

**Comment by Jacksgong** [comment]
@jiangtingfu 

参看这个commit修复的: [test: 修改Jkeybord的windows背景色为白色，以让切换的时候后面不是黑色](https://github.com/Jacksgong/JKeyboardPanelSwitch/commit/f4c4b7dcbfd2a614b8d721be559774139b26d8ab)

无论你的主题是什么，修改下windows的背景色，就可以处理你说的这个问题。

**Comment by wangkunhui** [comment]
@Jacksgong 但是如果设置activity的background的话  就会导致这个界面里面所有没有设置背景色的地方都会变成设置的background颜色
