### ISSUE TITLE
Demo 给voice按钮点击事件问题

### ISSUE THREAD

**Issue by sh1tge** [Jacksgong/JKeyboardPanelSwitch#30]
在demo中
给 voice_text_switch_iv 设置点击事件
当软键盘是弹起状态时 几乎点很多次才会触发一次 而当软键盘隐时 响应是没问题的

**Comment by Jacksgong** [comment]
我在 demo中的`ChattingResolvedActivity.java` 将其中的 [49 行](https://github.com/Jacksgong/JKeyboardPanelSwitch/blob/0a03dd190dc9e742e1e9a182f6811edee2e4ac63/app/src/main/java/cn/dreamtobe/kpswitch/demo/activity/ChattingResolvedActivity.java#L49)，将原本的:

```
mPlusIv = (ImageView) findViewById(R.id.plus_iv);
```

替换为:

```
mPlusIv = (ImageView) findViewById(R.id.voice_text_switch_iv);
```

---

这是我录制的[视频](https://cloud.githubusercontent.com/assets/6176417/15740401/4d8c7e8c-28e7-11e6-90ab-5ed6a9fe93e9.gif):

![1](https://cloud.githubusercontent.com/assets/6176417/15740401/4d8c7e8c-28e7-11e6-90ab-5ed6a9fe93e9.gif)

---

我怀疑你的应该是点击事件的问题。你看看你那边是否是有其他View在其上面或者周边是可点击的。将其点击事件消耗了。

**Comment by sh1tge** [comment]
这个问题我定位到了 部分机型确实是有问题 可能跟搜狗输入法有关. 换成系统默认就可以了
此问题在QQ以及QQ空间上也存在...之前我还以为是我手机那个区域触摸有问题..

**Comment by Jacksgong** [comment]
那挺诡异的，可否说说机型，我研究研究解决方案。

**Comment by sh1tge** [comment]
![screenshot_2016-08-01-10-43-44-059_com android se](https://cloud.githubusercontent.com/assets/7855225/17282191/fe7bff7a-57d5-11e6-9496-a5117c246140.png)

软键盘弹起的时候最左边的按钮点击无反应, 包括QQ QQ空间,你的demo 以及我项目
![1](https://cloud.githubusercontent.com/assets/7855225/17282304/11fe7f36-57d7-11e6-80c2-6a5c6e44e6df.png)
感觉就在默认情况下 搜狗就有个浮层 覆盖了这个按钮
![2](https://cloud.githubusercontent.com/assets/7855225/17282315/21f32d10-57d7-11e6-858f-29fb9838162e.png)

**Comment by Jacksgong** [comment]
恩。

**Comment by helloworldyx** [comment]
确实是搜狗输入法的问题，前几个月有遇到过，最新版已无该问题

**Comment by Jacksgong** [comment]
ok.
