### ISSUE TITLE
navigationBar的隐藏和显示，会使该库的逻辑错误。

### ISSUE THREAD

**Issue by feaoes** [Jacksgong/JKeyboardPanelSwitch#34]
华为手机下面的NavigationBar隐藏和显示，也通知OnGlobalLayout方法，你的逻辑误认为是键盘弹出导致的。

other issues:
如果使用Fragment的话，那么通过查找系统根节点进行监听
`final ViewGroup contentView = (ViewGroup) activity.findViewById(android.R.id.content);
contentView.getViewTreeObserver().
                addOnGlobalLayoutListener(
                        new KeyboardStatusListener(isFullScreen, isTranslucentStatus,
                                isFitSystemWindows,
                                contentView, target, listener));
`
当重复进入聊天Fragment的时候，会对聊天界面中的输入框进行多次注册，导致了重复的逻辑。

**Comment by Jacksgong** [comment]
该问题已经在这个PR中修复: https://github.com/Jacksgong/JKeyboardPanelSwitch/pull/33

等待[sollian](https://github.com/sollian)完善以后合入后会发布新的版本修复。

**Comment by Jacksgong** [comment]
Fixed since [v1.5.0](https://github.com/Jacksgong/JKeyboardPanelSwitch/releases/tag/v1.5.0).
