### ISSUE TITLE
三星S7手机，有一定几率会被遮盖住

### ISSUE THREAD

**Issue by SwordBearer** [Jacksgong/JKeyboardPanelSwitch#35]
首先感谢作者的代码，不过在使用过程中发现，
Translucent status with fitsSystemWindows=false 的情况下，在三星S7手机上，有一定概率，键盘会被遮挡住一部分，而遮挡的高度恰好就是状态栏的高度，效果图如下：

![image](https://cloud.githubusercontent.com/assets/1811579/17269240/dc87732e-5675-11e6-8ef1-0a180d040c1b.png)

试着给面板增加了状态栏的高度，但是在别的手机上又会有问题，求解 :)

**Comment by Jacksgong** [comment]
我现在手上没有S7，我周一到公司借台手机试试看，然后给个解决方案。

**Comment by Jacksgong** [comment]
已经修复了。主要原因是S7在这个主题下，获取到的 ActionBarOverlayLayout的Display Height 已经包含了 StatusBar的高度，导致在这种情况下 键盘的高度计算错误。

你可以拉最新代码下来试试。

---

我今天晚上应该会发一个新的版本。发了以后，我会在这个Issue下面评论的。

**Comment by Jacksgong** [comment]
Fixed since [v1.5.0](https://github.com/Jacksgong/JKeyboardPanelSwitch/releases/tag/v1.5.0).
