### ISSUE TITLE
聊天界面直接在Fragment上怎么处理？

### ISSUE THREAD

**Issue by Destiny01** [Jacksgong/JKeyboardPanelSwitch#38]
MainActivity上有4个Fragment，其中就有一个Fragment就是聊天页面，这种情况应该怎么办？

**Comment by Jacksgong** [comment]
没有影响的。在Fragment也是Attach在Activity上。

与Activity相同使用即可。

---

内部使用content_view，主要是用于判断，非本应用导致的布局变化。
