### ISSUE TITLE
想请问一下 最外层的布局必须是线性布局么？

### ISSUE THREAD

**Issue by eaglewangl** [Jacksgong/JKeyboardPanelSwitch#42]
如题， 我在demo中尝试用相对布局实现， 但是这样就无法定位panle出现的位置。那么如果布局非常复杂的情况下，线性布局嵌套层次就会非常多，比如斗鱼tv手机直播的页面。
能不能给个什么建议？

**Comment by Jacksgong** [comment]
不一定要是线性布局，没有太大影响。只要框架性的布局符合介绍中的就行，我们自己也是用在非常复杂的布局结构中。

**Comment by eaglewangl** [comment]
好的 我昨天也是发现自己思维进入了一个误区里面，所以才问了这个问题， 谢谢解答哦

**Comment by Jacksgong** [comment]
Okey.
