### ISSUE TITLE
无缘无故有下面的空白布局出来，不知道为啥

### ISSUE THREAD

**Issue by anjiao** [Jacksgong/JKeyboardPanelSwitch#47]
已解决

**Comment by anjiao** [comment]
还有下面这样的情况

**Comment by anjiao** [comment]
![4](https://cloud.githubusercontent.com/assets/6157486/19772444/cbb824c6-9c98-11e6-9bec-d455a317feb5.jpg)
![5](https://cloud.githubusercontent.com/assets/6157486/19772450/d10b8102-9c98-11e6-8d51-c94ca50db6d1.jpg)
![6](https://cloud.githubusercontent.com/assets/6157486/19772455/d7823e18-9c98-11e6-8ce1-774fe5a6c991.jpg)

**Comment by anjiao** [comment]
![7](https://cloud.githubusercontent.com/assets/6157486/19772588/4858143c-9c99-11e6-9de2-d237f1c2c344.jpg)
![8](https://cloud.githubusercontent.com/assets/6157486/19772591/4de40384-9c99-11e6-8bd0-d08552093516.jpg)
![9](https://cloud.githubusercontent.com/assets/6157486/19772596/5360eade-9c99-11e6-871b-037f887810d0.jpg)

**Comment by anjiao** [comment]
一口气 上传了很多图片 谢谢大神的开源 同时也希望你能帮我看看 ！！！

**Comment by anjiao** [comment]
我这里不只是在一个聊天界面那种  而是通过控制隐藏布局什么的  之前是可以的  但是 加了几个布局 之后 好像 就有问题了  我自认为我布局添加 肯定是正确的

**Comment by anjiao** [comment]
pannal 打印的高度 和我设置的一样 下面有阴影 那个问题  不知道为何了 感觉和底部多了  margin

**Comment by anjiao** [comment]
第二个  只显示  一行表情的 是代码的问题    上面的阴影 一直找不出原因

**Comment by jueran** [comment]
请问一下是怎么解决的，谢谢！
