### ISSUE TITLE
点击plusButton,不起作用

### ISSUE THREAD

**Issue by Erichkko** [Jacksgong/JKeyboardPanelSwitch#5]
当我点plus 按钮时setVisibility 会调用2次第一次visibility  == 0 第二次 visibility == 8,导致下面召唤不出来。
请问，是布局的问题，还是什么其他问题。

**Comment by Jacksgong** [comment]
demo中应该不存在该问题，如果是你代码中存在这个问题，因为前后相关性较强，可能需要你提供你的相关代码的demo的项目 通过发邮件(igzhenjie@gmail.com)或者github的方式给我看下，我给你看看问题所在。
