### ISSUE TITLE
使用中出现键盘将整个panel顶上去的情况

### ISSUE THREAD

**Issue by fanss** [Jacksgong/JKeyboardPanelSwitch#51]
![image](https://cloud.githubusercontent.com/assets/7117074/20654220/1afe29e6-b552-11e6-9f54-91c68af33dfc.png)
![image](https://cloud.githubusercontent.com/assets/7117074/20654228/29a47ef0-b552-11e6-8d83-3204da73ad78.png)
然后点击发送按钮右边的＋ 无法切换   然后 我把这个页面调整成全屏模式  就OK了  请问作者  这个可能是什么情况导致的呢？

**Comment by fanss** [comment]
问题已经找到了  是我子布局用错了  用成KPSwitchFSPanelLinearLayout  但是实际这个页面的主题 并不是全屏的

**Comment by Jacksgong** [comment]
好的。

**Comment by wang521314** [comment]
请问你怎么解决的我的子布局换成KPSwitchPanelLinearLayout后，点击按钮面板还是被键盘顶上去了啊，而且按钮就不管用了
