### ISSUE TITLE
输入法消失后输入法位置背景全黑遮盖

### ISSUE THREAD

**Issue by gitwizChen** [Jacksgong/JKeyboardPanelSwitch#56]
这是正常的输入法弹出后的界面:
![normal](https://raw.githubusercontent.com/gitwizChen/Assets/master/images/device-2017-02-22-194134.png)
这个是输入法隐藏后，下半部被黑色背景遮挡了:
![](https://raw.githubusercontent.com/gitwizChen/Assets/master/images/device-2017-02-22-194218.png)

**Comment by Jacksgong** [comment]
这个是因为window的背景是黑色，你在项目中改下主题中window的背景颜色即可。
