### ISSUE TITLE
hi~问个问题~关于沉浸状态,aJustResize不起作用

### ISSUE THREAD

**Issue by wangshaolei** [Jacksgong/JKeyboardPanelSwitch#59]
@Jacksgong Hi,我的项目用了你最早的键盘冲突解决代码。KeyboardRootLayout
现在这个版本 能适配到https://github.com/laobie/StatusBarUtil 和这个工具类并用吗，StatusBarUtil.setTransparent(Activity activity) 设置背景沉浸模式后，键盘监听不到了~

**Comment by ZhouBey** [comment]
解决了吗，当我设置全屏模式时，键盘监听不起作用了

**Comment by wangshaolei** [comment]
@ZhouBey 这个是状态栏造成高度与键盘配合造成。没有太完美的解决办法 。

**Comment by g19980115** [comment]
我之前也碰到这个问题，解决方法是，聊天的Activity中不使用StatusBarUtil，改用`rootView.fitsSystemWindows = true`就OK了

**Comment by Nstd** [comment]
使用这个库有类似问题，我们遇到的问题是，菜单面板不能正常隐藏
