### ISSUE TITLE
初始化时，怎样设置面板的高度

### ISSUE THREAD

**Issue by Fisherman91** [Jacksgong/JKeyboardPanelSwitch#65]
大神，第一次进界面，没有弹出系统默认键盘时，面板的高度为什么那么矮呢？ 改了dimens.xml文件里的panel_height无效。

**Comment by Jacksgong** [comment]
这个默认值内部机制是，如果还没有取到键盘高度，键盘高度是0，因此使用的是 允许的最小面板高度: `KeyboardUtil.MIN_KEYBOARD_HEIGHT`, 这个值是从`R.dimen.min_panel_height`中读取的：

#### 因此你只需要修改`dimens.xml`中的`min_panel_height`即可 (如果没有，就直接添加，因此这个值是在library中定义的，你上层定义了以后会自动merge为上层的值)。

**Comment by Fisherman91** [comment]
Thank you very very much！
