### ISSUE TITLE
PanelLayout的onMeasure()当mIsHide时，为什么要将width和height设置为0？

### ISSUE THREAD

**Issue by szitguy** [Jacksgong/JKeyboardPanelSwitch#7]
@Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        if (mIsHide) {
            setVisibility(View.GONE);
            widthMeasureSpec = MeasureSpec.makeMeasureSpec(0, MeasureSpec.EXACTLY);
            heightMeasureSpec = MeasureSpec.makeMeasureSpec(0, MeasureSpec.EXACTLY);
        }
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }

我尝试去掉设置成0的代码就会出现问题，输入法弹出来的时候，输入框被顶上，面板空白，然后我尝试一下改成下面的样子

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        if (mIsHide) {
            post(new Runnable() {
                @Override
                public void run() {
                    setVisibility(View.GONE);
                }
            });
        }
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }

也没有问题

**Comment by Jacksgong** [comment]
恩。`width` 和 `height` 设置为 0， 为了避免该帧(当mIsHide被设置为true时，已知该帧要画键盘弹起)面板还会影响其他布局，或者被画出导致冲突。

---

> P.S: 如果使用抛到UI线程Looper上去 `setVisibility` 会依赖于MessageQueue以及Looper调用周期，还可能受到 `Barrier` 的影响，因此有可能并不靠谱(可能还和rom有关)，而且把整个原本简单的事情搞复杂了。

**Comment by szitguy** [comment]
ok，大致了解了，谢谢

**Comment by Jacksgong** [comment]
:)
